# Generated by Django 3.1.4 on 2021-03-26 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='more_btn',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='direction',
        ),
        migrations.AddField(
            model_name='doctor',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='clinic.Direction', verbose_name='Направления'),
        ),
        migrations.AlterField(
            model_name='directionreviews',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_reviews', to='clinic.direction', verbose_name='Медицинское направление'),
        ),
        migrations.AlterField(
            model_name='directionreviews',
            name='video',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код видео (необязательно)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='short_description',
            field=models.TextField(max_length=200, verbose_name='СПЕЦИАЛИЗАЦИЯ и краткое описание'),
        ),
        migrations.AlterField(
            model_name='doctorreviews',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_reviews', to='clinic.doctor', verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='healing',
            name='direction',
            field=models.ManyToManyField(blank=True, related_name='healing', to='clinic.Direction', verbose_name='Направления'),
        ),
    ]
