# Generated by Django 3.1.4 on 2020-12-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='icon',
            field=models.URLField(blank=True, null=True, verbose_name='Иконка'),
        ),
    ]
