# Generated by Django 3.1.4 on 2021-06-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='title_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок акции 2'),
        ),
    ]
