# Generated by Django 3.1.4 on 2021-03-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20210326_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='show_on_home_page',
            field=models.BooleanField(default=False, verbose_name='На главной'),
        ),
    ]
