# Generated by Django 3.1.4 on 2020-12-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_direction_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Рейтинг доктора (от 1 до 5)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='views',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество просмотров страницы врача'),
        ),
    ]
