# Generated by Django 3.1.4 on 2021-06-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_action_title_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='title_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок акции 3'),
        ),
    ]
