# Generated by Django 3.1.4 on 2021-03-26 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_action_show_on_home_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Акция', 'verbose_name_plural': '3. Акции'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ('order',), 'verbose_name': 'Медицинское направление', 'verbose_name_plural': '1. Медицинские направления'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Доктор', 'verbose_name_plural': '2. Доктора'},
        ),
        migrations.RemoveField(
            model_name='healing',
            name='direction',
        ),
        migrations.AddField(
            model_name='healing',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healing', to='clinic.direction', verbose_name='Направление'),
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='directions',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='directions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='clinic.direction', verbose_name='Направления'),
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='doctors',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='clinic.doctor', verbose_name='Доктора'),
        ),
    ]
