# Generated by Django 3.1.4 on 2021-06-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_action_title_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='is_adults_direction',
            field=models.BooleanField(default=False, verbose_name='Взрослое'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='is_for_kids_direction',
            field=models.BooleanField(default=False, verbose_name='Детское'),
        ),
        migrations.AlterField(
            model_name='doctorreviews',
            name='video',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на видео (необязательно)'),
        ),
    ]
