# Generated by Django 3.1.4 on 2021-06-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20210620_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стаж работы'),
        ),
        migrations.AlterField(
            model_name='doctorreviews',
            name='video',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на видео (код после знака =)'),
        ),
    ]
