# Generated by Django 3.1.4 on 2021-03-26 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20210326_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='doctor',
        ),
        migrations.AddField(
            model_name='certificate',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='clinic.doctor', verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='doctorreviews',
            name='public_on_home_page',
            field=models.BooleanField(default=False, verbose_name='На главной'),
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='directions',
        ),
        migrations.AddField(
            model_name='videogallery',
            name='directions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='clinic.direction', verbose_name='Направления'),
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='doctors',
        ),
        migrations.AddField(
            model_name='videogallery',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='clinic.doctor', verbose_name='Доктора'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код видео'),
        ),
        migrations.DeleteModel(
            name='DirectionReviews',
        ),
    ]
