# Generated by Django 3.1.4 on 2020-12-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_remove_doctor_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='stages_of_treatment',
        ),
        migrations.AddField(
            model_name='healing',
            name='direction',
            field=models.ManyToManyField(blank=True, to='clinic.Direction', verbose_name='Направления'),
        ),
    ]
