# Generated by Django 3.1.4 on 2021-03-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20210326_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='public_on_home_page',
            field=models.BooleanField(default=False, verbose_name='На главной'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='views',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='doctorreviews',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
    ]
