# Generated by Django 3.1.4 on 2020-12-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20201207_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название изображения')),
                ('url', models.URLField(verbose_name='URL изображения')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('directions', models.ManyToManyField(blank=True, to='clinic.Direction', verbose_name='Направления')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название видео')),
                ('url', models.URLField(verbose_name='URL видео')),
                ('poster', models.URLField(verbose_name='Постер видео')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления видео')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('directions', models.ManyToManyField(blank=True, to='clinic.Direction', verbose_name='Направления')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='video',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='short_description',
            field=models.TextField(help_text='Будет использоваться в SEO', verbose_name='СПЕЦИАЛИЗАЦИЯ и краткое описание'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='videogallery',
            name='doctors',
            field=models.ManyToManyField(blank=True, to='clinic.Doctor', verbose_name='Доктора'),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='doctors',
            field=models.ManyToManyField(blank=True, to='clinic.Doctor', verbose_name='Доктора'),
        ),
    ]
