# Generated by Django 3.1.4 on 2021-03-26 06:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20210326_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreviews',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='healing',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
