# Generated by Django 3.1.4 on 2020-12-07 23:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20201208_0306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionreviews',
            options={'ordering': ('order',), 'verbose_name': 'Отзыв к направлению', 'verbose_name_plural': 'Отзывы к направлениям'},
        ),
        migrations.AlterField(
            model_name='directionreviews',
            name='avatar',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/space-developers/image/upload/v1607059811/Sanad/undraw_profile_pic_ic5t_qvsdyi.svg', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='directionreviews',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='directionreviews',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Отзыв'),
        ),
    ]
