# Generated by Django 3.1.4 on 2021-06-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20210623_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorreviews',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctorreviews',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='doctorreviews',
            name='text',
        ),
        migrations.AddField(
            model_name='doctorreviews',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для отзыва'),
        ),
    ]
