# Generated by Django 3.1.4 on 2021-03-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20210326_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализация врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='short_description',
            field=models.TextField(max_length=200, verbose_name='Краткое описание'),
        ),
    ]
