# Generated by Django 3.1.4 on 2020-12-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_doctor_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionreviews',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Отзыв к направлению', 'verbose_name_plural': 'Отзывы к направлениям'},
        ),
        migrations.AlterModelOptions(
            name='doctorreviews',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Отзыв к доктору', 'verbose_name_plural': 'Отзывы к докторам'},
        ),
        migrations.RemoveField(
            model_name='directionreviews',
            name='order',
        ),
        migrations.RemoveField(
            model_name='doctorreviews',
            name='order',
        ),
    ]
