# Generated by Django 3.1.4 on 2020-12-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_auto_20201209_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='action',
        ),
        migrations.AddField(
            model_name='action',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='actions', to='clinic.Direction', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='action',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='actions', to='clinic.Doctor', verbose_name='Доктор'),
        ),
        migrations.AddField(
            model_name='action',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='doctorreviews',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='clinic.doctor', verbose_name='Доктор'),
        ),
    ]
