# Generated by Django 3.1.4 on 2021-06-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_remove_direction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogallery',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='Превью для видео'),
        ),
    ]
