# Generated by Django 3.1.4 on 2021-06-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_videogallery_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorreviews',
            name='title',
        ),
    ]
