# Generated by Django 3.1.4 on 2020-12-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_auto_20201209_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
