# Generated by Django 3.1.4 on 2021-08-02 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_remove_doctorreviews_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок акции'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoint_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата приема')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('in_work', models.BooleanField(default=False, verbose_name='В работе')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appoints', to='clinic.doctor', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Заявка на прием',
                'verbose_name_plural': 'Заявки на прием',
                'ordering': ('-date',),
            },
        ),
    ]
