# Generated by Django 3.1.4 on 2020-12-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_action_more_btn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.URLField(verbose_name='Фото')),
                ('doctor', models.ManyToManyField(blank=True, related_name='certificates', to='clinic.Doctor', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Сертификат или грамота',
                'verbose_name_plural': 'Сертификаты и грамоты',
            },
        ),
    ]
