# Generated by Django 3.1.4 on 2021-08-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_auto_20210802_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-date',), 'verbose_name': 'Заявка на прием', 'verbose_name_plural': '5. Заявки на прием'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
