# Generated by Django 3.1.4 on 2020-12-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogallery',
            name='poster',
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='videos', to='clinic.Doctor', verbose_name='Доктора'),
        ),
    ]
