# Generated by Django 3.1.4 on 2021-08-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_auto_20210802_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appoint_date',
        ),
    ]
