# Generated by Django 3.1.4 on 2021-08-27 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_remove_appointment_appoint_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='clinic.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': '5. Услуги',
                'ordering': ('-date', 'order'),
            },
        ),
    ]
