# Generated by Django 3.1.4 on 2020-12-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20201209_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='images', to='clinic.Doctor', verbose_name='Доктора'),
        ),
    ]
