# Generated by Django 3.1.4 on 2020-12-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
    ]
