# Generated by Django 3.1.4 on 2020-12-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='images',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='videos',
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ManyToManyField(blank=True, to='blog.Post', verbose_name='Пост'),
        ),
        migrations.AddField(
            model_name='image',
            name='story',
            field=models.ManyToManyField(blank=True, to='blog.MedicalHistory', verbose_name='История болезни'),
        ),
        migrations.AddField(
            model_name='video',
            name='post',
            field=models.ManyToManyField(blank=True, to='blog.Post', verbose_name='Пост'),
        ),
        migrations.AddField(
            model_name='video',
            name='story',
            field=models.ManyToManyField(blank=True, to='blog.MedicalHistory', verbose_name='История болезни'),
        ),
    ]
