# Generated by Django 3.1.4 on 2021-03-26 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20210326_1054'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='miniature',
            field=models.URLField(blank=True, null=True, verbose_name='Миниатюра новости'),
        ),
        migrations.AddField(
            model_name='post',
            name='miniature',
            field=models.URLField(blank=True, null=True, verbose_name='Миниатюра новости'),
        ),
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='blog.post', verbose_name='Пост'),
        ),
        migrations.RemoveField(
            model_name='image',
            name='story',
        ),
        migrations.AddField(
            model_name='image',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='blog.medicalhistory', verbose_name='История болезни'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='direction',
            field=models.ManyToManyField(blank=True, related_name='stories', to='clinic.Direction', verbose_name='Направление'),
        ),
        migrations.RemoveField(
            model_name='video',
            name='post',
        ),
        migrations.AddField(
            model_name='video',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='blog.post', verbose_name='Пост'),
        ),
        migrations.RemoveField(
            model_name='video',
            name='story',
        ),
        migrations.AddField(
            model_name='video',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='blog.medicalhistory', verbose_name='История болезни'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код видео'),
        ),
    ]
