# Generated by Django 3.1.4 on 2021-03-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210326_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'ordering': ('order',), 'verbose_name': 'История болезни', 'verbose_name_plural': '2. Истории болезни'},
        ),
        migrations.AlterModelOptions(
            name='medicalhistoryreviews',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Комментарий к истории болезни', 'verbose_name_plural': '4. Комментарии к историям болезни'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('order',), 'verbose_name': 'Пост', 'verbose_name_plural': '1. Посты'},
        ),
        migrations.AlterModelOptions(
            name='postreviews',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Комментарий к посту', 'verbose_name_plural': '3. Комментарии к постам'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_action',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_news',
        ),
    ]
