# Generated by Django 3.1.4 on 2020-12-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201208_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt'),
        ),
    ]
