# Generated by Django 3.1.4 on 2020-12-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreviews',
            name='likes',
        ),
    ]
