# Generated by Django 3.1.4 on 2021-03-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210326_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
    ]
