# Generated by Django 3.1.4 on 2021-03-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210326_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='actual',
            field=models.BooleanField(default=False, verbose_name='Актуальное'),
        ),
        migrations.AddField(
            model_name='post',
            name='clinic_life',
            field=models.BooleanField(default=False, verbose_name='Жизнь клиники'),
        ),
    ]
