# Generated by Django 3.1.4 on 2021-03-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210326_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'ordering': ('-pub_date',), 'verbose_name': 'История болезни', 'verbose_name_plural': '2. Истории болезни'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Пост', 'verbose_name_plural': '1. Посты'},
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='post',
            name='order',
        ),
    ]
