# Generated by Django 3.1.4 on 2021-03-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210327_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='miniature',
            field=models.URLField(blank=True, null=True, verbose_name='Миниатюра'),
        ),
    ]
