# Generated by Django 3.1.4 on 2021-06-20 13:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страцниы о клинике')),
                ('sub_title', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Изображение для страницы о нас')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О клинике',
                'verbose_name_plural': '1. О клинике',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('icon', models.CharField(help_text='https://material.io/resources/icons/?style=baseline', max_length=255, verbose_name='Иконка')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': '4. Преимущества',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголвок для страницы контактов')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Подзаголовок')),
                ('phones', models.CharField(blank=True, help_text='Перечислить через запятую', max_length=150, null=True, verbose_name='Телефоны')),
                ('whatsapp', models.CharField(blank=True, help_text='просто 7 вместо 8 или +7', max_length=20, null=True, verbose_name='Whatsapp(в формате 7702xxxxxxxx)')),
                ('address', models.TextField(verbose_name='Адрес клиники')),
                ('frame', models.TextField(blank=True, null=True, verbose_name='Frame карты')),
                ('work_time', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': '5. Контакты',
            },
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title сайта (главная страница)')),
                ('description', models.TextField(verbose_name='Description сайта (главная страница)')),
                ('news_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для страницы новостей')),
                ('news_image', models.URLField(blank=True, null=True, verbose_name='Картинка для страницы новостей')),
                ('news_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание страницы новостей')),
                ('action_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для страницы акций')),
                ('action_image', models.URLField(blank=True, null=True, verbose_name='Картинка для страницы акций')),
                ('action_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Краткое описание страницы акций')),
                ('contacts_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для страницы контактов')),
                ('contacts_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Краткое описание страницы контактов')),
            ],
            options={
                'verbose_name': 'Заголовки страниц',
                'verbose_name_plural': '2. Заголовки страниц',
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_on_home', models.BooleanField(default=False, verbose_name='Показать на главной')),
                ('public_on_about', models.BooleanField(default=False, verbose_name='Показать на странице о клинике')),
                ('title', models.CharField(max_length=255, verbose_name='Название фото')),
                ('url', models.URLField(verbose_name='URL фото')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления видео')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': '8. Фото галерея',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок слайда')),
                ('title_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок слайда 2')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Картинка')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации слайда')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': '3. Слайды',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название соцсети')),
                ('icon', models.CharField(help_text='https://material.io/resources/icons/?style=baseline', max_length=255, verbose_name='Иконка')),
                ('url', models.URLField(verbose_name='Ссылка на страницу в сети')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Социальная сети',
                'verbose_name_plural': '6. Социальные сеть',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_on_home', models.BooleanField(default=False, verbose_name='Показать на главной')),
                ('title', models.CharField(max_length=255, verbose_name='Название видео')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код видео')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления видео')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': '7. Видео галерея',
            },
        ),
    ]
