# Generated by Django 3.1.4 on 2020-12-04 18:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('icon', models.CharField(help_text='https://material.io/resources/icons/?style=baseline', max_length=255, verbose_name='Иконка')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголвок для страницы контактов')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Подзаголовок (необязательно)')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон 2 (необзяательно)')),
                ('address', models.TextField(verbose_name='Адрес клиники')),
                ('work_time', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название видео')),
                ('url', models.URLField(verbose_name='URL видео')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления видео')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото галерея',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок слайда')),
                ('text', models.TextField(verbose_name='Текст на слайдере')),
                ('button_text', models.CharField(default='Подробнее', max_length=30, verbose_name='Текст на кнопке')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на кнопке')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации слайда')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название соцсети')),
                ('icon', models.CharField(help_text='https://material.io/resources/icons/?style=baseline', max_length=255, verbose_name='Иконка')),
                ('url', models.URLField(verbose_name='Ссылка на страницу в сети')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Кантакты',
                'verbose_name_plural': 'Кантакты',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название видео')),
                ('url', models.URLField(verbose_name='URL видео')),
                ('poster', models.URLField(verbose_name='Постер видео')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления видео')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео галерея',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страцниы о клинике')),
                ('sub_title', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('photos', models.ManyToManyField(blank=True, to='sanad.PhotoGallery', verbose_name='Фото галерея')),
                ('videos', models.ManyToManyField(blank=True, to='sanad.VideoGallery', verbose_name='Видео галерея')),
            ],
            options={
                'verbose_name': 'О клинике',
                'verbose_name_plural': 'О клинике',
            },
        ),
    ]
