# Generated by Django 3.1.4 on 2021-03-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='text',
        ),
        migrations.AddField(
            model_name='slider',
            name='title_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок слайда 2'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код видео'),
        ),
    ]
