# Generated by Django 3.1.4 on 2021-06-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='icon',
            field=models.URLField(blank=True, null=True, verbose_name='Иконка'),
        ),
    ]
