# Generated by Django 3.1.4 on 2020-12-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField(verbose_name='Логотип компании')),
                ('title', models.CharField(max_length=255, verbose_name='Title сайта')),
                ('description', models.TextField(verbose_name='Description сайта')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Header',
            },
        ),
    ]
