# Generated by Django 3.1.4 on 2021-06-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0002_auto_20210626_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='Баннер')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': '3.1 Баннеры',
            },
        ),
    ]
