# Generated by Django 3.1.4 on 2021-03-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0002_auto_20210326_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О клинике', 'verbose_name_plural': '1. О клинике'},
        ),
        migrations.AlterModelOptions(
            name='advantage',
            options={'ordering': ('order',), 'verbose_name': 'Преимущество', 'verbose_name_plural': '4. Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': '5. Контакты'},
        ),
        migrations.AlterModelOptions(
            name='maininfo',
            options={'verbose_name': 'Заголовки страниц', 'verbose_name_plural': '2. Заголовки страниц'},
        ),
        migrations.AlterModelOptions(
            name='photogallery',
            options={'verbose_name': 'Фото', 'verbose_name_plural': '8. Фото галерея'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('order',), 'verbose_name': 'Слайд', 'verbose_name_plural': '3. Слайды'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ('order',), 'verbose_name': 'Социальная сети', 'verbose_name_plural': '6. Социальные сеть'},
        ),
        migrations.AlterModelOptions(
            name='videogallery',
            options={'verbose_name': 'Видео', 'verbose_name_plural': '7. Видео галерея'},
        ),
    ]
