# Generated by Django 3.1.4 on 2020-12-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0002_maininfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maininfo',
            name='logo',
        ),
    ]
