# Generated by Django 3.1.4 on 2021-03-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0003_auto_20210326_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone_2',
        ),
        migrations.AddField(
            model_name='contacts',
            name='frame',
            field=models.TextField(blank=True, null=True, verbose_name='Frame карты'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phones',
            field=models.CharField(blank=True, help_text='Перечислить через запятую', max_length=150, null=True, verbose_name='Телефоны'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='просто 7 вместо 8 или +7', max_length=20, null=True, verbose_name='Whatsapp(в формате 7702xxxxxxxx)'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Подзаголовок'),
        ),
    ]
