# Generated by Django 3.1.4 on 2021-06-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0003_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('order',), 'verbose_name': 'Баннер', 'verbose_name_plural': '3.1 Баннеры'},
        ),
    ]
