# Generated by Django 3.1.4 on 2020-12-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0003_remove_maininfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Картинка'),
        ),
    ]
