# Generated by Django 3.1.4 on 2021-08-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0004_auto_20210627_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogallery',
            name='public_on_home',
        ),
        migrations.AddField(
            model_name='videogallery',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение'),
        ),
    ]
