# Generated by Django 3.1.4 on 2020-12-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0004_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button_url',
            field=models.SlugField(blank=True, null=True, verbose_name='Ссылка на кнопке'),
        ),
    ]
