# Generated by Django 3.1.4 on 2021-03-26 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0004_auto_20210326_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogallery',
            name='public_on_about',
        ),
    ]
