# Generated by Django 3.1.4 on 2020-12-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0005_auto_20201206_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ('order',), 'verbose_name': 'Социальные сети', 'verbose_name_plural': 'Социальная сеть'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_2',
            field=models.CharField(blank=True, help_text='просто 7 вместо 8 или +7', max_length=20, null=True, verbose_name='Whatsapp(в формате 7 702 xxx xx xxx)'),
        ),
    ]
