# Generated by Django 3.1.4 on 2020-12-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0006_auto_20201208_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maininfo',
            options={'verbose_name': 'Заголовки страниц', 'verbose_name_plural': 'Header'},
        ),
        migrations.AddField(
            model_name='maininfo',
            name='action_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Краткое описание страницы акций'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='action_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для страницы акций'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='contacts_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Краткое описание страницы контактов'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='contacts_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для страницы контактов'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='news_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание страницы новостей'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='news_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для страницы новостей'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='description',
            field=models.TextField(verbose_name='Description сайта (главная страница)'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title сайта (главная страница)'),
        ),
    ]
