# Generated by Django 3.1.4 on 2020-12-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0007_auto_20201211_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maininfo',
            options={'verbose_name': 'Заголовки страниц', 'verbose_name_plural': 'Заголовки страниц'},
        ),
        migrations.AddField(
            model_name='maininfo',
            name='action_image',
            field=models.URLField(blank=True, null=True, verbose_name='Картинка для страницы акций'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='news_image',
            field=models.URLField(blank=True, null=True, verbose_name='Картинка для страницы новостей'),
        ),
    ]
