# Generated by Django 3.1.4 on 2020-12-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0008_auto_20201211_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='about',
            name='videos',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение для страницы о нас'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='public_on_about',
            field=models.BooleanField(default=False, verbose_name='Показать на странице о клинике'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='public_on_home',
            field=models.BooleanField(default=False, verbose_name='Показать на главной'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='public_on_about',
            field=models.BooleanField(default=False, verbose_name='Показать на странице о клинике'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='public_on_home',
            field=models.BooleanField(default=False, verbose_name='Показать на главной'),
        ),
    ]
