# Generated by Django 3.1.4 on 2020-12-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanad', '0009_auto_20201211_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogallery',
            name='poster',
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название фото'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='url',
            field=models.URLField(verbose_name='URL фото'),
        ),
    ]
